(cl:defpackage assignment1-srv
  (:use )
  (:export
   "TSP"
   "<TSP-REQUEST>"
   "TSP-REQUEST"
   "<TSP-RESPONSE>"
   "TSP-RESPONSE"
   "TSPLIST"
   "<TSPLIST-REQUEST>"
   "TSPLIST-REQUEST"
   "<TSPLIST-RESPONSE>"
   "TSPLIST-RESPONSE"
   "TURTLESPAWN"
   "<TURTLESPAWN-REQUEST>"
   "TURTLESPAWN-REQUEST"
   "<TURTLESPAWN-RESPONSE>"
   "TURTLESPAWN-RESPONSE"
  ))

