(cl:defpackage assignment1-msg
  (:use )
  (:export
   "<STARTASSIGNMENTACTION>"
   "STARTASSIGNMENTACTION"
   "<STARTASSIGNMENTACTIONFEEDBACK>"
   "STARTASSIGNMENTACTIONFEEDBACK"
   "<STARTASSIGNMENTACTIONGOAL>"
   "STARTASSIGNMENTACTIONGOAL"
   "<STARTASSIGNMENTACTIONRESULT>"
   "STARTASSIGNMENTACTIONRESULT"
   "<STARTASSIGNMENTFEEDBACK>"
   "STARTASSIGNMENTFEEDBACK"
   "<STARTASSIGNMENTGOAL>"
   "STARTASSIGNMENTGOAL"
   "<STARTASSIGNMENTRESULT>"
   "STARTASSIGNMENTRESULT"
  ))

