; Auto-generated. Do not edit!


(cl:in-package assignment1-msg)


;//! \htmlinclude ConveyorGoal.msg.html

(cl:defclass <ConveyorGoal> (roslisp-msg-protocol:ros-message)
  ((maxSpawns
    :reader maxSpawns
    :initarg :maxSpawns
    :type cl:integer
    :initform 0))
)

(cl:defclass ConveyorGoal (<ConveyorGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ConveyorGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ConveyorGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name assignment1-msg:<ConveyorGoal> is deprecated: use assignment1-msg:ConveyorGoal instead.")))

(cl:ensure-generic-function 'maxSpawns-val :lambda-list '(m))
(cl:defmethod maxSpawns-val ((m <ConveyorGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader assignment1-msg:maxSpawns-val is deprecated.  Use assignment1-msg:maxSpawns instead.")
  (maxSpawns m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ConveyorGoal>) ostream)
  "Serializes a message object of type '<ConveyorGoal>"
  (cl:let* ((signed (cl:slot-value msg 'maxSpawns)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ConveyorGoal>) istream)
  "Deserializes a message object of type '<ConveyorGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'maxSpawns) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ConveyorGoal>)))
  "Returns string type for a message object of type '<ConveyorGoal>"
  "assignment1/ConveyorGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ConveyorGoal)))
  "Returns string type for a message object of type 'ConveyorGoal"
  "assignment1/ConveyorGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ConveyorGoal>)))
  "Returns md5sum for a message object of type '<ConveyorGoal>"
  "07cbe60e323004a5c1edebd284d349d6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ConveyorGoal)))
  "Returns md5sum for a message object of type 'ConveyorGoal"
  "07cbe60e323004a5c1edebd284d349d6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ConveyorGoal>)))
  "Returns full string definition for message of type '<ConveyorGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 maxSpawns~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ConveyorGoal)))
  "Returns full string definition for message of type 'ConveyorGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 maxSpawns~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ConveyorGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ConveyorGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ConveyorGoal
    (cl:cons ':maxSpawns (maxSpawns msg))
))
