; Auto-generated. Do not edit!


(cl:in-package assignment1-msg)


;//! \htmlinclude HuntTurtleActionGoal.msg.html

(cl:defclass <HuntTurtleActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type assignment1-msg:HuntTurtleGoal
    :initform (cl:make-instance 'assignment1-msg:HuntTurtleGoal)))
)

(cl:defclass HuntTurtleActionGoal (<HuntTurtleActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <HuntTurtleActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'HuntTurtleActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name assignment1-msg:<HuntTurtleActionGoal> is deprecated: use assignment1-msg:HuntTurtleActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <HuntTurtleActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader assignment1-msg:header-val is deprecated.  Use assignment1-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <HuntTurtleActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader assignment1-msg:goal_id-val is deprecated.  Use assignment1-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <HuntTurtleActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader assignment1-msg:goal-val is deprecated.  Use assignment1-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <HuntTurtleActionGoal>) ostream)
  "Serializes a message object of type '<HuntTurtleActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <HuntTurtleActionGoal>) istream)
  "Deserializes a message object of type '<HuntTurtleActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<HuntTurtleActionGoal>)))
  "Returns string type for a message object of type '<HuntTurtleActionGoal>"
  "assignment1/HuntTurtleActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'HuntTurtleActionGoal)))
  "Returns string type for a message object of type 'HuntTurtleActionGoal"
  "assignment1/HuntTurtleActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<HuntTurtleActionGoal>)))
  "Returns md5sum for a message object of type '<HuntTurtleActionGoal>"
  "3558c42c643fbfc139de069d81849149")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'HuntTurtleActionGoal)))
  "Returns md5sum for a message object of type 'HuntTurtleActionGoal"
  "3558c42c643fbfc139de069d81849149")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<HuntTurtleActionGoal>)))
  "Returns full string definition for message of type '<HuntTurtleActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%HuntTurtleGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: assignment1/HuntTurtleGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32 hunterX~%float32 hunterY~%float32 hunterTheta~%string hunterName~%float32 targetX~%float32 targetY~%float32 targetTheta~%string targetName~%int32 targetId~%bool kill~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'HuntTurtleActionGoal)))
  "Returns full string definition for message of type 'HuntTurtleActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%HuntTurtleGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: assignment1/HuntTurtleGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32 hunterX~%float32 hunterY~%float32 hunterTheta~%string hunterName~%float32 targetX~%float32 targetY~%float32 targetTheta~%string targetName~%int32 targetId~%bool kill~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <HuntTurtleActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <HuntTurtleActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'HuntTurtleActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
