; Auto-generated. Do not edit!


(cl:in-package assignment1-msg)


;//! \htmlinclude StartAssignmentGoal.msg.html

(cl:defclass <StartAssignmentGoal> (roslisp-msg-protocol:ros-message)
  ((numberOfTurtles
    :reader numberOfTurtles
    :initarg :numberOfTurtles
    :type cl:integer
    :initform 0))
)

(cl:defclass StartAssignmentGoal (<StartAssignmentGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StartAssignmentGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StartAssignmentGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name assignment1-msg:<StartAssignmentGoal> is deprecated: use assignment1-msg:StartAssignmentGoal instead.")))

(cl:ensure-generic-function 'numberOfTurtles-val :lambda-list '(m))
(cl:defmethod numberOfTurtles-val ((m <StartAssignmentGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader assignment1-msg:numberOfTurtles-val is deprecated.  Use assignment1-msg:numberOfTurtles instead.")
  (numberOfTurtles m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StartAssignmentGoal>) ostream)
  "Serializes a message object of type '<StartAssignmentGoal>"
  (cl:let* ((signed (cl:slot-value msg 'numberOfTurtles)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StartAssignmentGoal>) istream)
  "Deserializes a message object of type '<StartAssignmentGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'numberOfTurtles) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StartAssignmentGoal>)))
  "Returns string type for a message object of type '<StartAssignmentGoal>"
  "assignment1/StartAssignmentGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StartAssignmentGoal)))
  "Returns string type for a message object of type 'StartAssignmentGoal"
  "assignment1/StartAssignmentGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StartAssignmentGoal>)))
  "Returns md5sum for a message object of type '<StartAssignmentGoal>"
  "60f669674938de301cb2e14e9642c336")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StartAssignmentGoal)))
  "Returns md5sum for a message object of type 'StartAssignmentGoal"
  "60f669674938de301cb2e14e9642c336")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StartAssignmentGoal>)))
  "Returns full string definition for message of type '<StartAssignmentGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 numberOfTurtles~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StartAssignmentGoal)))
  "Returns full string definition for message of type 'StartAssignmentGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 numberOfTurtles~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StartAssignmentGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StartAssignmentGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'StartAssignmentGoal
    (cl:cons ':numberOfTurtles (numberOfTurtles msg))
))
