; Auto-generated. Do not edit!


(cl:in-package assignment1-msg)


;//! \htmlinclude StartAssignmentResult.msg.html

(cl:defclass <StartAssignmentResult> (roslisp-msg-protocol:ros-message)
  ((turtlesCollected
    :reader turtlesCollected
    :initarg :turtlesCollected
    :type cl:string
    :initform ""))
)

(cl:defclass StartAssignmentResult (<StartAssignmentResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StartAssignmentResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StartAssignmentResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name assignment1-msg:<StartAssignmentResult> is deprecated: use assignment1-msg:StartAssignmentResult instead.")))

(cl:ensure-generic-function 'turtlesCollected-val :lambda-list '(m))
(cl:defmethod turtlesCollected-val ((m <StartAssignmentResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader assignment1-msg:turtlesCollected-val is deprecated.  Use assignment1-msg:turtlesCollected instead.")
  (turtlesCollected m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StartAssignmentResult>) ostream)
  "Serializes a message object of type '<StartAssignmentResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'turtlesCollected))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'turtlesCollected))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StartAssignmentResult>) istream)
  "Deserializes a message object of type '<StartAssignmentResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'turtlesCollected) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'turtlesCollected) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StartAssignmentResult>)))
  "Returns string type for a message object of type '<StartAssignmentResult>"
  "assignment1/StartAssignmentResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StartAssignmentResult)))
  "Returns string type for a message object of type 'StartAssignmentResult"
  "assignment1/StartAssignmentResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StartAssignmentResult>)))
  "Returns md5sum for a message object of type '<StartAssignmentResult>"
  "e5a48e16d6948dbcf97c66dba03b84a7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StartAssignmentResult)))
  "Returns md5sum for a message object of type 'StartAssignmentResult"
  "e5a48e16d6948dbcf97c66dba03b84a7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StartAssignmentResult>)))
  "Returns full string definition for message of type '<StartAssignmentResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%string turtlesCollected~%#int32 collectionSequence~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StartAssignmentResult)))
  "Returns full string definition for message of type 'StartAssignmentResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%string turtlesCollected~%#int32 collectionSequence~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StartAssignmentResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'turtlesCollected))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StartAssignmentResult>))
  "Converts a ROS message object to a list"
  (cl:list 'StartAssignmentResult
    (cl:cons ':turtlesCollected (turtlesCollected msg))
))
