; Auto-generated. Do not edit!


(cl:in-package assignment1-msg)


;//! \htmlinclude StartAssignmentFeedback.msg.html

(cl:defclass <StartAssignmentFeedback> (roslisp-msg-protocol:ros-message)
  ((progress
    :reader progress
    :initarg :progress
    :type cl:string
    :initform ""))
)

(cl:defclass StartAssignmentFeedback (<StartAssignmentFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StartAssignmentFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StartAssignmentFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name assignment1-msg:<StartAssignmentFeedback> is deprecated: use assignment1-msg:StartAssignmentFeedback instead.")))

(cl:ensure-generic-function 'progress-val :lambda-list '(m))
(cl:defmethod progress-val ((m <StartAssignmentFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader assignment1-msg:progress-val is deprecated.  Use assignment1-msg:progress instead.")
  (progress m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StartAssignmentFeedback>) ostream)
  "Serializes a message object of type '<StartAssignmentFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'progress))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'progress))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StartAssignmentFeedback>) istream)
  "Deserializes a message object of type '<StartAssignmentFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'progress) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'progress) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StartAssignmentFeedback>)))
  "Returns string type for a message object of type '<StartAssignmentFeedback>"
  "assignment1/StartAssignmentFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StartAssignmentFeedback)))
  "Returns string type for a message object of type 'StartAssignmentFeedback"
  "assignment1/StartAssignmentFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StartAssignmentFeedback>)))
  "Returns md5sum for a message object of type '<StartAssignmentFeedback>"
  "4e8180fd8cffb84e555b1c648b3e7287")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StartAssignmentFeedback)))
  "Returns md5sum for a message object of type 'StartAssignmentFeedback"
  "4e8180fd8cffb84e555b1c648b3e7287")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StartAssignmentFeedback>)))
  "Returns full string definition for message of type '<StartAssignmentFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%string progress~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StartAssignmentFeedback)))
  "Returns full string definition for message of type 'StartAssignmentFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%string progress~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StartAssignmentFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'progress))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StartAssignmentFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'StartAssignmentFeedback
    (cl:cons ':progress (progress msg))
))
