// Generated by gencpp from file turtle_spawn/InitialSceneResponse.msg
// DO NOT EDIT!


#ifndef TURTLE_SPAWN_MESSAGE_INITIALSCENERESPONSE_H
#define TURTLE_SPAWN_MESSAGE_INITIALSCENERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_spawn
{
template <class ContainerAllocator>
struct InitialSceneResponse_
{
  typedef InitialSceneResponse_<ContainerAllocator> Type;

  InitialSceneResponse_()
    : tsp_turtles()
    , conveyor_turtle()
    , catch_turtle()  {
    }
  InitialSceneResponse_(const ContainerAllocator& _alloc)
    : tsp_turtles(_alloc)
    , conveyor_turtle(_alloc)
    , catch_turtle(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _tsp_turtles_type;
  _tsp_turtles_type tsp_turtles;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _conveyor_turtle_type;
  _conveyor_turtle_type conveyor_turtle;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _catch_turtle_type;
  _catch_turtle_type catch_turtle;





  typedef boost::shared_ptr< ::turtle_spawn::InitialSceneResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_spawn::InitialSceneResponse_<ContainerAllocator> const> ConstPtr;

}; // struct InitialSceneResponse_

typedef ::turtle_spawn::InitialSceneResponse_<std::allocator<void> > InitialSceneResponse;

typedef boost::shared_ptr< ::turtle_spawn::InitialSceneResponse > InitialSceneResponsePtr;
typedef boost::shared_ptr< ::turtle_spawn::InitialSceneResponse const> InitialSceneResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_spawn::InitialSceneResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_spawn::InitialSceneResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtle_spawn

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtle_spawn::InitialSceneResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_spawn::InitialSceneResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_spawn::InitialSceneResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_spawn::InitialSceneResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_spawn::InitialSceneResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_spawn::InitialSceneResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_spawn::InitialSceneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "402e653149fd07543d076d54895e4f5e";
  }

  static const char* value(const ::turtle_spawn::InitialSceneResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x402e653149fd0754ULL;
  static const uint64_t static_value2 = 0x3d076d54895e4f5eULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_spawn::InitialSceneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_spawn/InitialSceneResponse";
  }

  static const char* value(const ::turtle_spawn::InitialSceneResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_spawn::InitialSceneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string tsp_turtles\n"
"string conveyor_turtle\n"
"string catch_turtle\n"
;
  }

  static const char* value(const ::turtle_spawn::InitialSceneResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_spawn::InitialSceneResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tsp_turtles);
      stream.next(m.conveyor_turtle);
      stream.next(m.catch_turtle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitialSceneResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_spawn::InitialSceneResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_spawn::InitialSceneResponse_<ContainerAllocator>& v)
  {
    s << indent << "tsp_turtles: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.tsp_turtles);
    s << indent << "conveyor_turtle: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.conveyor_turtle);
    s << indent << "catch_turtle: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.catch_turtle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_SPAWN_MESSAGE_INITIALSCENERESPONSE_H
