// Generated by gencpp from file turtle_spawn/InitialSceneRequest.msg
// DO NOT EDIT!


#ifndef TURTLE_SPAWN_MESSAGE_INITIALSCENEREQUEST_H
#define TURTLE_SPAWN_MESSAGE_INITIALSCENEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_spawn
{
template <class ContainerAllocator>
struct InitialSceneRequest_
{
  typedef InitialSceneRequest_<ContainerAllocator> Type;

  InitialSceneRequest_()
    : numberOfTSPTurtles(0)  {
    }
  InitialSceneRequest_(const ContainerAllocator& _alloc)
    : numberOfTSPTurtles(0)  {
  (void)_alloc;
    }



   typedef int32_t _numberOfTSPTurtles_type;
  _numberOfTSPTurtles_type numberOfTSPTurtles;





  typedef boost::shared_ptr< ::turtle_spawn::InitialSceneRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_spawn::InitialSceneRequest_<ContainerAllocator> const> ConstPtr;

}; // struct InitialSceneRequest_

typedef ::turtle_spawn::InitialSceneRequest_<std::allocator<void> > InitialSceneRequest;

typedef boost::shared_ptr< ::turtle_spawn::InitialSceneRequest > InitialSceneRequestPtr;
typedef boost::shared_ptr< ::turtle_spawn::InitialSceneRequest const> InitialSceneRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_spawn::InitialSceneRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_spawn::InitialSceneRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtle_spawn

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtle_spawn::InitialSceneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_spawn::InitialSceneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_spawn::InitialSceneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_spawn::InitialSceneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_spawn::InitialSceneRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_spawn::InitialSceneRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_spawn::InitialSceneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f54c22ea8d163b5734adfe96724e1fec";
  }

  static const char* value(const ::turtle_spawn::InitialSceneRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf54c22ea8d163b57ULL;
  static const uint64_t static_value2 = 0x34adfe96724e1fecULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_spawn::InitialSceneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_spawn/InitialSceneRequest";
  }

  static const char* value(const ::turtle_spawn::InitialSceneRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_spawn::InitialSceneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 numberOfTSPTurtles\n"
;
  }

  static const char* value(const ::turtle_spawn::InitialSceneRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_spawn::InitialSceneRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.numberOfTSPTurtles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitialSceneRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_spawn::InitialSceneRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_spawn::InitialSceneRequest_<ContainerAllocator>& v)
  {
    s << indent << "numberOfTSPTurtles: ";
    Printer<int32_t>::stream(s, indent + "  ", v.numberOfTSPTurtles);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_SPAWN_MESSAGE_INITIALSCENEREQUEST_H
