// Generated by gencpp from file assignment1/ConveyorGoal.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT1_MESSAGE_CONVEYORGOAL_H
#define ASSIGNMENT1_MESSAGE_CONVEYORGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment1
{
template <class ContainerAllocator>
struct ConveyorGoal_
{
  typedef ConveyorGoal_<ContainerAllocator> Type;

  ConveyorGoal_()
    : maxSpawns(0)  {
    }
  ConveyorGoal_(const ContainerAllocator& _alloc)
    : maxSpawns(0)  {
  (void)_alloc;
    }



   typedef int32_t _maxSpawns_type;
  _maxSpawns_type maxSpawns;





  typedef boost::shared_ptr< ::assignment1::ConveyorGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment1::ConveyorGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ConveyorGoal_

typedef ::assignment1::ConveyorGoal_<std::allocator<void> > ConveyorGoal;

typedef boost::shared_ptr< ::assignment1::ConveyorGoal > ConveyorGoalPtr;
typedef boost::shared_ptr< ::assignment1::ConveyorGoal const> ConveyorGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment1::ConveyorGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment1::ConveyorGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment1::ConveyorGoal_<ContainerAllocator1> & lhs, const ::assignment1::ConveyorGoal_<ContainerAllocator2> & rhs)
{
  return lhs.maxSpawns == rhs.maxSpawns;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment1::ConveyorGoal_<ContainerAllocator1> & lhs, const ::assignment1::ConveyorGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::ConveyorGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::ConveyorGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::ConveyorGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::ConveyorGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::ConveyorGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::ConveyorGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment1::ConveyorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "07cbe60e323004a5c1edebd284d349d6";
  }

  static const char* value(const ::assignment1::ConveyorGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x07cbe60e323004a5ULL;
  static const uint64_t static_value2 = 0xc1edebd284d349d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment1::ConveyorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment1/ConveyorGoal";
  }

  static const char* value(const ::assignment1::ConveyorGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment1::ConveyorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int32 maxSpawns\n"
;
  }

  static const char* value(const ::assignment1::ConveyorGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment1::ConveyorGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.maxSpawns);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConveyorGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment1::ConveyorGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment1::ConveyorGoal_<ContainerAllocator>& v)
  {
    s << indent << "maxSpawns: ";
    Printer<int32_t>::stream(s, indent + "  ", v.maxSpawns);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT1_MESSAGE_CONVEYORGOAL_H
