// Generated by gencpp from file assignment1/HuntTurtleFeedback.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT1_MESSAGE_HUNTTURTLEFEEDBACK_H
#define ASSIGNMENT1_MESSAGE_HUNTTURTLEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment1
{
template <class ContainerAllocator>
struct HuntTurtleFeedback_
{
  typedef HuntTurtleFeedback_<ContainerAllocator> Type;

  HuntTurtleFeedback_()
    : progressBar()
    , progress(0.0)
    , timeRemaining()  {
    }
  HuntTurtleFeedback_(const ContainerAllocator& _alloc)
    : progressBar(_alloc)
    , progress(0.0)
    , timeRemaining(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _progressBar_type;
  _progressBar_type progressBar;

   typedef float _progress_type;
  _progress_type progress;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _timeRemaining_type;
  _timeRemaining_type timeRemaining;





  typedef boost::shared_ptr< ::assignment1::HuntTurtleFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment1::HuntTurtleFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct HuntTurtleFeedback_

typedef ::assignment1::HuntTurtleFeedback_<std::allocator<void> > HuntTurtleFeedback;

typedef boost::shared_ptr< ::assignment1::HuntTurtleFeedback > HuntTurtleFeedbackPtr;
typedef boost::shared_ptr< ::assignment1::HuntTurtleFeedback const> HuntTurtleFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment1::HuntTurtleFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment1::HuntTurtleFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace assignment1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'assignment1': ['/home/adam/catkin_ws/devel/share/assignment1/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::HuntTurtleFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::HuntTurtleFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::HuntTurtleFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::HuntTurtleFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::HuntTurtleFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::HuntTurtleFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment1::HuntTurtleFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ebd791a2e9bf1e98d90417c0e82beb3e";
  }

  static const char* value(const ::assignment1::HuntTurtleFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xebd791a2e9bf1e98ULL;
  static const uint64_t static_value2 = 0xd90417c0e82beb3eULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment1::HuntTurtleFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment1/HuntTurtleFeedback";
  }

  static const char* value(const ::assignment1::HuntTurtleFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment1::HuntTurtleFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"string progressBar\n"
"float32 progress\n"
"string timeRemaining\n"
;
  }

  static const char* value(const ::assignment1::HuntTurtleFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment1::HuntTurtleFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.progressBar);
      stream.next(m.progress);
      stream.next(m.timeRemaining);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HuntTurtleFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment1::HuntTurtleFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment1::HuntTurtleFeedback_<ContainerAllocator>& v)
  {
    s << indent << "progressBar: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.progressBar);
    s << indent << "progress: ";
    Printer<float>::stream(s, indent + "  ", v.progress);
    s << indent << "timeRemaining: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.timeRemaining);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT1_MESSAGE_HUNTTURTLEFEEDBACK_H
