// Generated by gencpp from file assignment1/HuntTurtleActionGoal.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT1_MESSAGE_HUNTTURTLEACTIONGOAL_H
#define ASSIGNMENT1_MESSAGE_HUNTTURTLEACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <assignment1/HuntTurtleGoal.h>

namespace assignment1
{
template <class ContainerAllocator>
struct HuntTurtleActionGoal_
{
  typedef HuntTurtleActionGoal_<ContainerAllocator> Type;

  HuntTurtleActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  HuntTurtleActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::assignment1::HuntTurtleGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::assignment1::HuntTurtleActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment1::HuntTurtleActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct HuntTurtleActionGoal_

typedef ::assignment1::HuntTurtleActionGoal_<std::allocator<void> > HuntTurtleActionGoal;

typedef boost::shared_ptr< ::assignment1::HuntTurtleActionGoal > HuntTurtleActionGoalPtr;
typedef boost::shared_ptr< ::assignment1::HuntTurtleActionGoal const> HuntTurtleActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment1::HuntTurtleActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment1::HuntTurtleActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment1::HuntTurtleActionGoal_<ContainerAllocator1> & lhs, const ::assignment1::HuntTurtleActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment1::HuntTurtleActionGoal_<ContainerAllocator1> & lhs, const ::assignment1::HuntTurtleActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::HuntTurtleActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::HuntTurtleActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::HuntTurtleActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::HuntTurtleActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::HuntTurtleActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::HuntTurtleActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment1::HuntTurtleActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3558c42c643fbfc139de069d81849149";
  }

  static const char* value(const ::assignment1::HuntTurtleActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3558c42c643fbfc1ULL;
  static const uint64_t static_value2 = 0x39de069d81849149ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment1::HuntTurtleActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment1/HuntTurtleActionGoal";
  }

  static const char* value(const ::assignment1::HuntTurtleActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment1::HuntTurtleActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"HuntTurtleGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: assignment1/HuntTurtleGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"float32 hunterX\n"
"float32 hunterY\n"
"float32 hunterTheta\n"
"string hunterName\n"
"float32 targetX\n"
"float32 targetY\n"
"float32 targetTheta\n"
"string targetName\n"
"int32 targetId\n"
"bool kill\n"
;
  }

  static const char* value(const ::assignment1::HuntTurtleActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment1::HuntTurtleActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HuntTurtleActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment1::HuntTurtleActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment1::HuntTurtleActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::assignment1::HuntTurtleGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT1_MESSAGE_HUNTTURTLEACTIONGOAL_H
