// Generated by gencpp from file assignment1/HuntTurtleResult.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT1_MESSAGE_HUNTTURTLERESULT_H
#define ASSIGNMENT1_MESSAGE_HUNTTURTLERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment1
{
template <class ContainerAllocator>
struct HuntTurtleResult_
{
  typedef HuntTurtleResult_<ContainerAllocator> Type;

  HuntTurtleResult_()
    : status()
    , time(0.0)  {
    }
  HuntTurtleResult_(const ContainerAllocator& _alloc)
    : status(_alloc)
    , time(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;

   typedef float _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::assignment1::HuntTurtleResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment1::HuntTurtleResult_<ContainerAllocator> const> ConstPtr;

}; // struct HuntTurtleResult_

typedef ::assignment1::HuntTurtleResult_<std::allocator<void> > HuntTurtleResult;

typedef boost::shared_ptr< ::assignment1::HuntTurtleResult > HuntTurtleResultPtr;
typedef boost::shared_ptr< ::assignment1::HuntTurtleResult const> HuntTurtleResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment1::HuntTurtleResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment1::HuntTurtleResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment1::HuntTurtleResult_<ContainerAllocator1> & lhs, const ::assignment1::HuntTurtleResult_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment1::HuntTurtleResult_<ContainerAllocator1> & lhs, const ::assignment1::HuntTurtleResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::HuntTurtleResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::HuntTurtleResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::HuntTurtleResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::HuntTurtleResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::HuntTurtleResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::HuntTurtleResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment1::HuntTurtleResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fc38c7a693cc0fee1486d3f8d3005fb";
  }

  static const char* value(const ::assignment1::HuntTurtleResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fc38c7a693cc0feULL;
  static const uint64_t static_value2 = 0xe1486d3f8d3005fbULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment1::HuntTurtleResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment1/HuntTurtleResult";
  }

  static const char* value(const ::assignment1::HuntTurtleResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment1::HuntTurtleResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"string status\n"
"float32 time\n"
;
  }

  static const char* value(const ::assignment1::HuntTurtleResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment1::HuntTurtleResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HuntTurtleResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment1::HuntTurtleResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment1::HuntTurtleResult_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
    s << indent << "time: ";
    Printer<float>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT1_MESSAGE_HUNTTURTLERESULT_H
