// Generated by gencpp from file assignment1/StartAssignmentResult.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT1_MESSAGE_STARTASSIGNMENTRESULT_H
#define ASSIGNMENT1_MESSAGE_STARTASSIGNMENTRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment1
{
template <class ContainerAllocator>
struct StartAssignmentResult_
{
  typedef StartAssignmentResult_<ContainerAllocator> Type;

  StartAssignmentResult_()
    : turtlesCollected()  {
    }
  StartAssignmentResult_(const ContainerAllocator& _alloc)
    : turtlesCollected(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _turtlesCollected_type;
  _turtlesCollected_type turtlesCollected;





  typedef boost::shared_ptr< ::assignment1::StartAssignmentResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment1::StartAssignmentResult_<ContainerAllocator> const> ConstPtr;

}; // struct StartAssignmentResult_

typedef ::assignment1::StartAssignmentResult_<std::allocator<void> > StartAssignmentResult;

typedef boost::shared_ptr< ::assignment1::StartAssignmentResult > StartAssignmentResultPtr;
typedef boost::shared_ptr< ::assignment1::StartAssignmentResult const> StartAssignmentResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment1::StartAssignmentResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment1::StartAssignmentResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment1::StartAssignmentResult_<ContainerAllocator1> & lhs, const ::assignment1::StartAssignmentResult_<ContainerAllocator2> & rhs)
{
  return lhs.turtlesCollected == rhs.turtlesCollected;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment1::StartAssignmentResult_<ContainerAllocator1> & lhs, const ::assignment1::StartAssignmentResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::StartAssignmentResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::StartAssignmentResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::StartAssignmentResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::StartAssignmentResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::StartAssignmentResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::StartAssignmentResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment1::StartAssignmentResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e5a48e16d6948dbcf97c66dba03b84a7";
  }

  static const char* value(const ::assignment1::StartAssignmentResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe5a48e16d6948dbcULL;
  static const uint64_t static_value2 = 0xf97c66dba03b84a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment1::StartAssignmentResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment1/StartAssignmentResult";
  }

  static const char* value(const ::assignment1::StartAssignmentResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment1::StartAssignmentResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"string turtlesCollected\n"
"#int32 collectionSequence\n"
;
  }

  static const char* value(const ::assignment1::StartAssignmentResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment1::StartAssignmentResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.turtlesCollected);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartAssignmentResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment1::StartAssignmentResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment1::StartAssignmentResult_<ContainerAllocator>& v)
  {
    s << indent << "turtlesCollected: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.turtlesCollected);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT1_MESSAGE_STARTASSIGNMENTRESULT_H
