// Generated by gencpp from file assignment1/StartAssignmentGoal.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT1_MESSAGE_STARTASSIGNMENTGOAL_H
#define ASSIGNMENT1_MESSAGE_STARTASSIGNMENTGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment1
{
template <class ContainerAllocator>
struct StartAssignmentGoal_
{
  typedef StartAssignmentGoal_<ContainerAllocator> Type;

  StartAssignmentGoal_()
    : numberOfTurtles(0)  {
    }
  StartAssignmentGoal_(const ContainerAllocator& _alloc)
    : numberOfTurtles(0)  {
  (void)_alloc;
    }



   typedef int32_t _numberOfTurtles_type;
  _numberOfTurtles_type numberOfTurtles;





  typedef boost::shared_ptr< ::assignment1::StartAssignmentGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment1::StartAssignmentGoal_<ContainerAllocator> const> ConstPtr;

}; // struct StartAssignmentGoal_

typedef ::assignment1::StartAssignmentGoal_<std::allocator<void> > StartAssignmentGoal;

typedef boost::shared_ptr< ::assignment1::StartAssignmentGoal > StartAssignmentGoalPtr;
typedef boost::shared_ptr< ::assignment1::StartAssignmentGoal const> StartAssignmentGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment1::StartAssignmentGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment1::StartAssignmentGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment1::StartAssignmentGoal_<ContainerAllocator1> & lhs, const ::assignment1::StartAssignmentGoal_<ContainerAllocator2> & rhs)
{
  return lhs.numberOfTurtles == rhs.numberOfTurtles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment1::StartAssignmentGoal_<ContainerAllocator1> & lhs, const ::assignment1::StartAssignmentGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::StartAssignmentGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::StartAssignmentGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::StartAssignmentGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::StartAssignmentGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::StartAssignmentGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::StartAssignmentGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment1::StartAssignmentGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60f669674938de301cb2e14e9642c336";
  }

  static const char* value(const ::assignment1::StartAssignmentGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60f669674938de30ULL;
  static const uint64_t static_value2 = 0x1cb2e14e9642c336ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment1::StartAssignmentGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment1/StartAssignmentGoal";
  }

  static const char* value(const ::assignment1::StartAssignmentGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment1::StartAssignmentGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"int32 numberOfTurtles\n"
;
  }

  static const char* value(const ::assignment1::StartAssignmentGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment1::StartAssignmentGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.numberOfTurtles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartAssignmentGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment1::StartAssignmentGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment1::StartAssignmentGoal_<ContainerAllocator>& v)
  {
    s << indent << "numberOfTurtles: ";
    Printer<int32_t>::stream(s, indent + "  ", v.numberOfTurtles);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT1_MESSAGE_STARTASSIGNMENTGOAL_H
