// Generated by gencpp from file assignment1/TspResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT1_MESSAGE_TSPRESPONSE_H
#define ASSIGNMENT1_MESSAGE_TSPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment1
{
template <class ContainerAllocator>
struct TspResponse_
{
  typedef TspResponse_<ContainerAllocator> Type;

  TspResponse_()
    : sequence()  {
    }
  TspResponse_(const ContainerAllocator& _alloc)
    : sequence(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sequence_type;
  _sequence_type sequence;





  typedef boost::shared_ptr< ::assignment1::TspResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment1::TspResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TspResponse_

typedef ::assignment1::TspResponse_<std::allocator<void> > TspResponse;

typedef boost::shared_ptr< ::assignment1::TspResponse > TspResponsePtr;
typedef boost::shared_ptr< ::assignment1::TspResponse const> TspResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment1::TspResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment1::TspResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment1::TspResponse_<ContainerAllocator1> & lhs, const ::assignment1::TspResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sequence == rhs.sequence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment1::TspResponse_<ContainerAllocator1> & lhs, const ::assignment1::TspResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::TspResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::TspResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::TspResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::TspResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::TspResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::TspResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment1::TspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2810e4b1ee8df76ac8a9a36d5becb93c";
  }

  static const char* value(const ::assignment1::TspResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2810e4b1ee8df76aULL;
  static const uint64_t static_value2 = 0xc8a9a36d5becb93cULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment1::TspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment1/TspResponse";
  }

  static const char* value(const ::assignment1::TspResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment1::TspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sequence\n"
;
  }

  static const char* value(const ::assignment1::TspResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment1::TspResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sequence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TspResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment1::TspResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment1::TspResponse_<ContainerAllocator>& v)
  {
    s << indent << "sequence: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sequence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT1_MESSAGE_TSPRESPONSE_H
