// Generated by gencpp from file assignment1/TspRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT1_MESSAGE_TSPREQUEST_H
#define ASSIGNMENT1_MESSAGE_TSPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment1
{
template <class ContainerAllocator>
struct TspRequest_
{
  typedef TspRequest_<ContainerAllocator> Type;

  TspRequest_()
    : turtles()  {
    }
  TspRequest_(const ContainerAllocator& _alloc)
    : turtles(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _turtles_type;
  _turtles_type turtles;





  typedef boost::shared_ptr< ::assignment1::TspRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment1::TspRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TspRequest_

typedef ::assignment1::TspRequest_<std::allocator<void> > TspRequest;

typedef boost::shared_ptr< ::assignment1::TspRequest > TspRequestPtr;
typedef boost::shared_ptr< ::assignment1::TspRequest const> TspRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment1::TspRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment1::TspRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace assignment1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'assignment1': ['/home/adam/catkin_ws/devel/share/assignment1/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::TspRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::TspRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::TspRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::TspRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::TspRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::TspRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment1::TspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d0e809b0cc068311f8979aaa5e9b8bf";
  }

  static const char* value(const ::assignment1::TspRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d0e809b0cc06831ULL;
  static const uint64_t static_value2 = 0x1f8979aaa5e9b8bfULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment1::TspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment1/TspRequest";
  }

  static const char* value(const ::assignment1::TspRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment1::TspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string turtles\n"
;
  }

  static const char* value(const ::assignment1::TspRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment1::TspRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.turtles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TspRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment1::TspRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment1::TspRequest_<ContainerAllocator>& v)
  {
    s << indent << "turtles: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.turtles);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT1_MESSAGE_TSPREQUEST_H
