// Generated by gencpp from file assignment1/TurtleSpawnResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT1_MESSAGE_TURTLESPAWNRESPONSE_H
#define ASSIGNMENT1_MESSAGE_TURTLESPAWNRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment1
{
template <class ContainerAllocator>
struct TurtleSpawnResponse_
{
  typedef TurtleSpawnResponse_<ContainerAllocator> Type;

  TurtleSpawnResponse_()
    : turtles()  {
    }
  TurtleSpawnResponse_(const ContainerAllocator& _alloc)
    : turtles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _turtles_type;
  _turtles_type turtles;





  typedef boost::shared_ptr< ::assignment1::TurtleSpawnResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment1::TurtleSpawnResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TurtleSpawnResponse_

typedef ::assignment1::TurtleSpawnResponse_<std::allocator<void> > TurtleSpawnResponse;

typedef boost::shared_ptr< ::assignment1::TurtleSpawnResponse > TurtleSpawnResponsePtr;
typedef boost::shared_ptr< ::assignment1::TurtleSpawnResponse const> TurtleSpawnResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment1::TurtleSpawnResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment1::TurtleSpawnResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace assignment1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'assignment1': ['/home/adam/catkin_ws/devel/share/assignment1/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::TurtleSpawnResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::TurtleSpawnResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::TurtleSpawnResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::TurtleSpawnResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::TurtleSpawnResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::TurtleSpawnResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment1::TurtleSpawnResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5cfa4f7983516bb1fa09ba771f01902";
  }

  static const char* value(const ::assignment1::TurtleSpawnResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5cfa4f7983516bbULL;
  static const uint64_t static_value2 = 0x1fa09ba771f01902ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment1::TurtleSpawnResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment1/TurtleSpawnResponse";
  }

  static const char* value(const ::assignment1::TurtleSpawnResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment1::TurtleSpawnResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] turtles\n"
"\n"
;
  }

  static const char* value(const ::assignment1::TurtleSpawnResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment1::TurtleSpawnResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.turtles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtleSpawnResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment1::TurtleSpawnResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment1::TurtleSpawnResponse_<ContainerAllocator>& v)
  {
    s << indent << "turtles[]" << std::endl;
    for (size_t i = 0; i < v.turtles.size(); ++i)
    {
      s << indent << "  turtles[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.turtles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT1_MESSAGE_TURTLESPAWNRESPONSE_H
