// Generated by gencpp from file assignment1/TurtleSpawnRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT1_MESSAGE_TURTLESPAWNREQUEST_H
#define ASSIGNMENT1_MESSAGE_TURTLESPAWNREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment1
{
template <class ContainerAllocator>
struct TurtleSpawnRequest_
{
  typedef TurtleSpawnRequest_<ContainerAllocator> Type;

  TurtleSpawnRequest_()
    : turtleCount(0)  {
    }
  TurtleSpawnRequest_(const ContainerAllocator& _alloc)
    : turtleCount(0)  {
  (void)_alloc;
    }



   typedef int32_t _turtleCount_type;
  _turtleCount_type turtleCount;





  typedef boost::shared_ptr< ::assignment1::TurtleSpawnRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment1::TurtleSpawnRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TurtleSpawnRequest_

typedef ::assignment1::TurtleSpawnRequest_<std::allocator<void> > TurtleSpawnRequest;

typedef boost::shared_ptr< ::assignment1::TurtleSpawnRequest > TurtleSpawnRequestPtr;
typedef boost::shared_ptr< ::assignment1::TurtleSpawnRequest const> TurtleSpawnRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment1::TurtleSpawnRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment1::TurtleSpawnRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace assignment1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'assignment1': ['/home/adam/catkin_ws/devel/share/assignment1/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::TurtleSpawnRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::TurtleSpawnRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::TurtleSpawnRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::TurtleSpawnRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::TurtleSpawnRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::TurtleSpawnRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment1::TurtleSpawnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71d37b1d2fe27ce9d264372080e332e2";
  }

  static const char* value(const ::assignment1::TurtleSpawnRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71d37b1d2fe27ce9ULL;
  static const uint64_t static_value2 = 0xd264372080e332e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment1::TurtleSpawnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment1/TurtleSpawnRequest";
  }

  static const char* value(const ::assignment1::TurtleSpawnRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment1::TurtleSpawnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 turtleCount\n"
;
  }

  static const char* value(const ::assignment1::TurtleSpawnRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment1::TurtleSpawnRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.turtleCount);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtleSpawnRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment1::TurtleSpawnRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment1::TurtleSpawnRequest_<ContainerAllocator>& v)
  {
    s << indent << "turtleCount: ";
    Printer<int32_t>::stream(s, indent + "  ", v.turtleCount);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT1_MESSAGE_TURTLESPAWNREQUEST_H
