// Auto-generated. Do not edit!

// (in-package assignment1.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ConveyorGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.maxSpawns = null;
    }
    else {
      if (initObj.hasOwnProperty('maxSpawns')) {
        this.maxSpawns = initObj.maxSpawns
      }
      else {
        this.maxSpawns = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ConveyorGoal
    // Serialize message field [maxSpawns]
    bufferOffset = _serializer.int32(obj.maxSpawns, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ConveyorGoal
    let len;
    let data = new ConveyorGoal(null);
    // Deserialize message field [maxSpawns]
    data.maxSpawns = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'assignment1/ConveyorGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '07cbe60e323004a5c1edebd284d349d6';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int32 maxSpawns
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ConveyorGoal(null);
    if (msg.maxSpawns !== undefined) {
      resolved.maxSpawns = msg.maxSpawns;
    }
    else {
      resolved.maxSpawns = 0
    }

    return resolved;
    }
};

module.exports = ConveyorGoal;
