// Auto-generated. Do not edit!

// (in-package assignment1.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class StartAssignmentGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.numberOfTurtles = null;
    }
    else {
      if (initObj.hasOwnProperty('numberOfTurtles')) {
        this.numberOfTurtles = initObj.numberOfTurtles
      }
      else {
        this.numberOfTurtles = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type StartAssignmentGoal
    // Serialize message field [numberOfTurtles]
    bufferOffset = _serializer.int32(obj.numberOfTurtles, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type StartAssignmentGoal
    let len;
    let data = new StartAssignmentGoal(null);
    // Deserialize message field [numberOfTurtles]
    data.numberOfTurtles = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'assignment1/StartAssignmentGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '60f669674938de301cb2e14e9642c336';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    int32 numberOfTurtles
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new StartAssignmentGoal(null);
    if (msg.numberOfTurtles !== undefined) {
      resolved.numberOfTurtles = msg.numberOfTurtles;
    }
    else {
      resolved.numberOfTurtles = 0
    }

    return resolved;
    }
};

module.exports = StartAssignmentGoal;
