// Auto-generated. Do not edit!

// (in-package assignment1.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class StartAssignmentResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.turtlesCollected = null;
    }
    else {
      if (initObj.hasOwnProperty('turtlesCollected')) {
        this.turtlesCollected = initObj.turtlesCollected
      }
      else {
        this.turtlesCollected = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type StartAssignmentResult
    // Serialize message field [turtlesCollected]
    bufferOffset = _serializer.string(obj.turtlesCollected, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type StartAssignmentResult
    let len;
    let data = new StartAssignmentResult(null);
    // Deserialize message field [turtlesCollected]
    data.turtlesCollected = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.turtlesCollected.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'assignment1/StartAssignmentResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e5a48e16d6948dbcf97c66dba03b84a7';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    string turtlesCollected
    #int32 collectionSequence
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new StartAssignmentResult(null);
    if (msg.turtlesCollected !== undefined) {
      resolved.turtlesCollected = msg.turtlesCollected;
    }
    else {
      resolved.turtlesCollected = ''
    }

    return resolved;
    }
};

module.exports = StartAssignmentResult;
